name: gifski
version: 0.8.5
summary: gifski
description: |
   GIF encoder based on libimagequant (pngquant).
   Squeezes maximum possible quality from the awful
   GIF format. https://gif.ski

# FIXME:
# armhf build failed with:
#   "error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256'"
#   "failed to make network request"
#   "channel-rust-stable.toml.sha256: timed out"
# ppc64el build failed with:
#   "Failed to run '/root/.cargo/bin/cargo +stable fetch --manifest-path /build/gifski-brlin/parts/gifski/src/Cargo.toml' for 'gifski': Exited with code -4."
# s390x build failed with:
#   "rustup: unknown CPU type: s390x"
architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: i386
    run-on: i386
  - build-on: arm64
    run-on: arm64

base: core18
confinement: strict

apps:
  gifski:
    command: gifski
    plugs:
    - home

parts:
  gifski:
    source-type: git
    source: https://github.com/ImageOptim/gifski.git
    source-tag: 0.8.5
    plugin: rust
    rust-features:
      - openmp
    stage-packages:
      - libgomp1
